### ISSUE TITLE
Extend Speech to text transcription time

### ISSUE THREAD

**Issue by Sadiq-Naizam** [wit-ai/wit-unity#79]
I've been using wit ai 's Speech to text feature and it has been fantastic. But one issue I keep facing is that I cannot transcribe multiple sentences at once. If I take a pause at the end of the sentence, the activation stops. I would have to start over again. I want the ability to define a wait period before the app experience deactivates So far I've tried tweaking the Min Keep alive time and Min Keep Alive volume in the App Voice Experience script but that doesn't seem to do anything.

**Comment by yolanother** [comment]
Are you using this for voice commands or dictation purposes? It sounds like you're using it with the intent of recognizing multiple sentences for dictation. If that is the case I'd recommend using the dictation module instead of the appvoiceexperience module, it is more tailored to capturing long form text. AppVoiceExperience is designed to handle short input voice commands and will endpoint as soon as it thinks it has enough to process a voice command.
